// export const InsuranceProviders = [
//   { label: "21st Century Insurance" },
//   { label: "AAA" },
//   { label: "AARP" },
//   { label: "Acceptance" },
//   { label: "Adrianas Insurance" },
//   { label: "Alfa" },
//   { label: "Allied" },
//   { label: "Allstate" },
//   { label: "American Family" },
//   { label: "American Modern" },
//   { label: "Ameriprise" },
//   { label: "Amica" },
//   { label: "Arbella" },
//   { label: "Aspire General" },
//   { label: "Auto-Owners" },
//   { label: "Bear River Mutual" },
//   { label: "Bristol West" },
//   { label: "California Casualty" },
//   { label: "Chubb" },
//   { label: "Cincinnati Insurance Company" },
//   { label: "Commonwealth Casualty" },
//   { label: "Costco" },
//   { label: "Country Financial" },
//   { label: "CURE Insurance" },
//   { label: "Dairyland" },
//   { label: "Direct Auto" },
//   { label: "Electric" },
//   { label: "Elephant Insurance" },
//   { label: "Encompass" },
//   { label: "Erie Insurance" },
//   { label: "New York Central Mutual" },
//   { label: "Esurance" },
//   { label: "NJM Insurance" },
//   { label: "Falcon Insurance" },
//   { label: "Ohio Mutual" },
//   { label: "Farm Bureau" },
//   { label: "Oregon Mutual" },
//   { label: "Farmers" },
//   { label: "Plymouth Rock" },
//   { label: "Fiesta" },
//   { label: "Progressive" },
//   { label: "First Chicago" },
//   { label: "Pronto" },
//   { label: "Foremost" },
//   { label: "Pure Insurance" },
//   { label: "Fred Loya" },
//   { label: "Root Insurance" },
//   { label: "Freedom National" },
//   { label: "Safe Auto" },
//   { label: "Freeway Insurance" },
//   { label: "Safeco" },
//   { label: "Gainsco" },
//   { label: "Safety" },
//   { label: "Geico" },
//   { label: "Secura" },
//   { label: "GoAuto" },
//   { label: "Shelter" },
//   { label: "Good2Go" },
//   { label: "State Farm" },
//   { label: "Grange Insurance" },
//   { label: "Stillwater Insurance" },
//   { label: "Great Florida" },
//   { label: "Tesla Insurance" },
//   { label: "Homesite" },
//   { label: "The General" },
//   { label: "Infinity" },
//   { label: "The Hanover" },
//   { label: "Kemper" },
//   { label: "The Hartford" },
//   { label: "Liberty Mutual" },
//   { label: "Tower Hill" },
//   { label: "Mapfre" },
//   { label: "Travelers" },
//   { label: "Maryland Automobile Insurance" },
//   { label: "Fund" },
//   { label: "Trustage" },
//   { label: "Mercury" },
//   { label: "United Auto" },
//   { label: "MetLife" },
//   { label: "USAA" },
//   { label: "Metromile" },
//   { label: "Vermont Mutual" },
//   { label: "National General" },
//   { label: "Wawanesa" },
//   { label: "Nationwide" },
//   { label: "Westfield" },
// ];

// export const coverageTypes = [{ label: "Standard" }, { label: "Full" }];