export const InsuranceProviders = {
  companies: [
    "21st Century Insurance",
    "AAA",
    "AARP",
    "Acceptance",
    "Adrianas Insurance",
    "Alfa",
    "Allied",
    "Allstate",
    "American Family",
    "American Modern",
    "Ameriprise",
    "Amica",
    "Arbella",
    "Aspire General",
    "Auto-Owners",
    "Bear River Mutual",
    "Bristol West",
    "California Casualty",
    "Chubb",
    "Cincinnati Insurance Company",
    "Commonwealth Casualty",
    "Costco",
    "Country Financial",
    "CURE Insurance",
    "Dairyland",
    "Direct Auto",
    "Electric",
    "Elephant Insurance",
    "Encompass",
    "Erie Insurance",
    "New York Central Mutual",
    "Esurance",
    "NJM Insurance",
    "Falcon Insurance",
    "Ohio Mutual",
    "Farm Bureau",
    "Oregon Mutual",
    "Farmers",
    "Plymouth Rock",
    "Fiesta",
    "Progressive",
    "First Chicago",
    "Pronto",
    "Foremost",
    "Pure Insurance",
    "Fred Loya",
    "Root Insurance",
    "Freedom National",
    "Safe Auto",
    "Freeway Insurance",
    "Safeco",
    "Gainsco",
    "Safety",
    "Geico",
    "Secura",
    "GoAuto",
    "Shelter",
    "Good2Go",
    "State Farm",
    "Grange Insurance",
    "Stillwater Insurance",
    "Great Florida",
    "Tesla Insurance",
    "Homesite",
    "The General",
    "Infinity",
    "The Hanover",
    "Kemper",
    "The Hartford",
    "Liberty Mutual",
    "Tower Hill",
    "Mapfre",
    "Travelers",
    "Maryland Automobile Insurance",
    "Fund",
    "Trustage",
    "Mercury",
    "United Auto",
    "MetLife",
    "USAA",
    "Metromile",
    "Vermont Mutual",
    "National General",
    "Wawanesa",
    "Nationwide",
    "Westfield",
  ],
  coverageType: ["Basic", "Standard", "Full"],
};
